import React,{useEffect,useState,useRef} from 'react';
import {Folder,FileText,ChevronRight,ArrowLeft,Plus,Upload,Download,Save,Pencil,Trash2,Search,X,BookOpen} from 'lucide-react';
import {api} from './api';
import Editor from './Editor';
const join=(a,b)=>a?`${a}/${b}`:b;
export default function Files({memory=false,onError}){
  const [dir,setDir]=useState(''),[entries,setEntries]=useState([]),[projects,setProjects]=useState([]),[project,setProject]=useState(''),[query,setQuery]=useState(''),[opened,setOpened]=useState(null),[content,setContent]=useState(''),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[dialog,setDialog]=useState(null),[name,setName]=useState('');
  const upload=useRef();
  useEffect(()=>{window.agyHasUnsavedChanges=dirty;const warn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>{window.agyHasUnsavedChanges=false;window.removeEventListener('beforeunload',warn);};},[dirty]);
  const run=async fn=>{try{setBusy(true);await fn();}catch(e){onError(e.message);}finally{setBusy(false);}};
  async function refresh(){if(memory&&!project){setEntries([]);return;}setEntries(await api(query?`/search?q=${encodeURIComponent(query)}&path=${encodeURIComponent(dir)}`:`/files?path=${encodeURIComponent(dir)}`));}
  useEffect(()=>{run(async()=>{if(memory)setProjects((await api('/files')).filter(x=>x.directory));else await refresh();});},[]);
  useEffect(()=>{const timer=setTimeout(()=>run(refresh),query?300:0);return()=>clearTimeout(timer);},[dir,query,project]);
  function leave(){return !dirty||window.confirm('Discard unsaved changes?');}
  async function open(entry){if(entry.symlink){onError('Symbolic links are unavailable in the file interface.');return;}if(!leave())return;if(entry.directory){setDir(entry.path);setQuery('');setOpened(null);setDirty(false);}else await run(async()=>{const data=await api('/file?path='+encodeURIComponent(entry.path));setOpened(entry);setContent(data.content);setDirty(false);});}
  function showDialog(kind,entry){setName(kind==='rename'?entry.name:'');setDialog({kind,entry});}
  async function submit(event){event.preventDefault();await run(async()=>{
    const {kind,entry}=dialog;
    if(kind==='delete')await api('/file',{method:'DELETE',body:{path:entry.path}});
    else {if(!name.trim()||name.includes('/')||['.','..'].includes(name)){throw new Error('Enter a single file or folder name.');}
      if(kind==='rename')await api('/rename',{method:'POST',body:{path:entry.path,to:join(entry.path.split('/').slice(0,-1).join('/'),name)}});
      if(kind==='folder')await api('/folder',{method:'POST',body:{path:join(dir,name)}});
      if(kind==='file')await api('/file',{method:'PUT',body:{path:join(dir,name),content:'',create:true}});
    }
    if(opened?.path===entry?.path){setOpened(null);setDirty(false);}setDialog(null);await refresh();
  });}
  async function selectProject(value){if(!leave())return;setProject(value);setOpened(null);setDirty(false);setQuery('');if(!value){setDir('');return;}const memoryPath=join(value,'.private-memory');await run(async()=>{try{await api('/files?path='+encodeURIComponent(memoryPath));}catch(e){if(e.message.includes('ENOENT'))await api('/folder',{method:'POST',body:{path:memoryPath}});else throw e;}setDir(memoryPath);});}
  return <section className="content-page">
    <div className="section-heading"><div><span className="eyebrow">{memory?'YOUR CONTEXT, YOUR CHOICE':'PERSISTENT WORKSPACE'}</span><h1>{memory?'Project memory':'Files'}</h1><p>{memory?'Plain-text notes. Read by AGY only when you ask.':'Real files. Normal repositories. Always yours.'}</p></div><div className="heading-symbol">{memory?<BookOpen/>:<Folder/>}</div></div>
    {memory&&<label className="project-select">Project<select value={project} onChange={e=>selectProject(e.target.value)}><option value="">Choose a project</option>{projects.map(p=><option key={p.path} value={p.path}>{p.name}</option>)}</select></label>}
    {!memory||project?<>
    <div className="file-actions"><button onClick={()=>{if(!leave())return;setOpened(null);setDirty(false);setDir(dir.split('/').slice(0,-1).join('/'));setQuery('');}} disabled={!dir || (memory&&dir===join(project,'.private-memory'))}><ArrowLeft size={16}/></button><span className="breadcrumb">projects{dir&&' / '+dir.split('/').join(' / ')}</span><button onClick={()=>showDialog('file')}><Plus size={16}/>File</button><button onClick={()=>showDialog('folder')}><Plus size={16}/>Folder</button><button onClick={()=>upload.current.click()}><Upload size={16}/><span className="hide-small">Upload</span></button><input hidden ref={upload} type="file" multiple onChange={e=>{const selected=[...e.target.files];run(async()=>{for(const file of selected)await api('/upload?path='+encodeURIComponent(join(dir,file.name)),{method:'POST',headers:{'content-type':'application/octet-stream'},body:file});await refresh();});e.target.value='';}}/></div>
    <label className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find a file by name…"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X size={14}/></button>}</label>
    <div className={'file-layout'+(opened?' has-editor':'')}><div className="file-list" aria-busy={busy}>{entries.map(entry=><div className={'file-row'+(opened?.path===entry.path?' active':'')} key={entry.path}><button className="file-open" onClick={()=>open(entry)}>{entry.directory?<Folder size={18}/>:<FileText size={18}/>}<span>{entry.name}{query&&<small>{entry.path}</small>}</span>{entry.directory?<ChevronRight size={15}/>:<small>{entry.size<1024?entry.size+' B':(entry.size/1024).toFixed(1)+' KB'}</small>}</button>{!entry.directory&&<a className="icon-button" aria-label={'Download '+entry.name} href={'/api/download?path='+encodeURIComponent(entry.path)}><Download size={14}/></a>}<button className="icon-button" aria-label={'Rename '+entry.name} onClick={()=>showDialog('rename',entry)}><Pencil size={14}/></button><button className="icon-button danger" aria-label={'Delete '+entry.name} onClick={()=>showDialog('delete',entry)}><Trash2 size={14}/></button></div>)}{!entries.length&&<div className="empty-state"><Folder size={32}/><h3>{query?'No matching files':'Room for your next project'}</h3><p>{query?'Try another filename.':memory?'Create a note, decision log, or handoff.':'Create a folder here, upload files, or clone a repository in the terminal.'}</p></div>}</div>
    {opened&&<div className="editor-panel"><div className="editor-bar"><span>{opened.name}{dirty&&<b> •</b>}</span><a className="icon-button" href={'/api/download?path='+encodeURIComponent(opened.path)} title="Download"><Download size={16}/></a><button disabled={!dirty||busy} className="save-button" onClick={()=>run(async()=>{await api('/file',{method:'PUT',body:{path:opened.path,content}});setDirty(false);})}><Save size={14}/>Save</button><button className="icon-button" aria-label="Close editor" onClick={()=>{if(leave()){setOpened(null);setDirty(false);}}}><X size={16}/></button></div><Editor key={opened.path} file={opened.path} content={content} onChange={text=>{setContent(text);setDirty(true);}}/></div>}</div>
    </>:<div className="empty-state spacious"><BookOpen size={36}/><h3>A place to leave yourself a note</h3><p>Choose a project to view its .private-memory folder.<br/>Your notes are never added to prompts automatically.</p></div>}
    {dialog&&<div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="section-heading"><h2>{dialog.kind==='delete'?'Delete '+dialog.entry.name+'?':dialog.kind==='rename'?'Rename':'New '+dialog.kind}</h2><button type="button" className="icon-button" onClick={()=>setDialog(null)} aria-label="Close"><X/></button></div>{dialog.kind==='delete'?<p>This permanently deletes this {dialog.entry.directory?'folder and its contents':'file'} from the workspace.</p>:<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Name" required/>}<button disabled={busy} className={dialog.kind==='delete'?'primary destructive':'primary'}>{dialog.kind==='delete'?'Delete permanently':dialog.kind==='rename'?'Rename':'Create'}</button></form></div>}
  </section>;
}
