import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {TerminalSquare,Folder,Globe,BookOpen,Settings,ArrowUpRight,LogOut,ShieldCheck,RefreshCw,Check,Lock,ArrowRight,X,Wifi,ExternalLink} from 'lucide-react';
import Terminal from './Terminal';
import Files from './Files';
import {api,setCsrf} from './api';
import './styles.css';
const sections=[['AGY',TerminalSquare],['Files',Folder],['Browser',Globe],['Memory',BookOpen],['Settings',Settings]];
function Brand(){return <div className="brand"><span className="brand-mark">a<span>✳</span></span><span>AGY<span className="brand-sub">PERSONAL WORKSPACE</span></span></div>;}
function Browser({onError}){
  const [data,setData]=useState(null),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[control,setControl]=useState(false);
  async function refresh(){try{setBusy(true);const d=await api('/browser');setData(d);setSelected(s=>d.sessions.some(x=>x.id===s)?s:d.sessions[0]?.id||'');}catch(e){onError(e.message);}finally{setBusy(false);}}
  useEffect(()=>{refresh();const timer=setInterval(refresh,15000);return()=>clearInterval(timer);},[]);
  const active=data?.sessions.find(x=>x.id===selected);
  return <section className="content-page"><div className="section-heading"><div><span className="eyebrow">A WINDOW INTO THE WEB</span><h1>Browser</h1><p>Follow your agent’s browser. Step in when you need to.</p></div><button onClick={refresh} disabled={busy}><RefreshCw size={16}/>Refresh</button></div>
    {active?<><div className="browser-bar"><select aria-label="Browser session" value={selected} onChange={e=>{setSelected(e.target.value);setControl(false);}}>{data.sessions.map(s=><option key={s.id} value={s.id}>{s.id.slice(0,12)}</option>)}</select><button className={control?'primary':''} onClick={()=>setControl(!control)}>{control?'Return to watch mode':'Take control'}</button><a href={active.liveUrl} target="_blank" rel="noreferrer">Open live view<ExternalLink size={14}/></a></div><p className="browser-hint">{control?'Manual input enabled. Ask AGY to pause before entering credentials; tell it when you are ready to continue.':'Watching live. Take control to interact with the browser.'}</p><div className="browser-frame"><iframe title="Browserbase live session" src={active.liveUrl} allow="clipboard-read; clipboard-write"/>{!control&&<div className="watch-overlay" aria-label="Watch only"/>}</div></>:<div className="empty-state spacious"><div className="empty-orbit"><Globe size={40}/></div><h3>{data?.configured?'Ready when your agent is':'Connect your cloud browser'}</h3><p>{data?.configured?'Ask AGY to use Browserbase through MCP. Active sessions will appear here automatically.':'Add Browserbase credentials to the workspace service in Railway, then enable the Browserbase MCP in AGY.'}</p><a className="text-link" href="https://www.browserbase.com" target="_blank" rel="noreferrer">Browserbase<ArrowUpRight size={15}/></a></div>}
  </section>;
}
function Preferences({onError,onLogout}){
  const [status,setStatus]=useState(null);useEffect(()=>{api('/status').then(setStatus).catch(e=>onError(e.message));},[]);
  return <section className="content-page"><div className="section-heading"><div><span className="eyebrow">MADE FOR ONE</span><h1>Settings</h1><p>Your private connection to a persistent Linux workspace.</p></div><div className="heading-symbol"><Settings/></div></div><div className="settings-grid"><article className="settings-card"><ShieldCheck size={22}/><h3>Private by design</h3><p>Password-protected access. Secure sessions. One workspace, one owner.</p><dl><dt>Session</dt><dd>30 days</dd><dt>Workspace</dt><dd>Private network</dd><dt>Agent</dt><dd>{status?.agentInstalled?'Antigravity CLI installed':'Checking…'}</dd></dl></article><article className="settings-card"><Folder size={22}/><h3>A home that stays</h3><p>Files and native AGY state live on the persistent Railway volume.</p><code>{status?.home||'/home/agy'}</code><p className="small">Terminal sessions survive browser disconnects. A workspace restart ends running processes; persisted files remain.</p></article><article className="settings-card"><TerminalSquare size={22}/><h3>You’re at the controls</h3><p>Run <code>agy</code> in the terminal to start. AGY handles its own login and approval flow.</p><p className="small">No generated prompts, automatic restarts, or hidden continuation. Memory is read only when you ask.</p></article><article className="settings-card"><Globe size={22}/><h3>On your Home Screen</h3><p>In Safari, tap Share → Add to Home Screen. Open AGY for the standalone experience.</p><p className="small">Use the Paste toolbar for large prompts and the native selection menu to copy.</p></article></div><button className="logout" onClick={onLogout}><LogOut size={16}/>Sign out</button></section>;
}
function App(){
  const [auth,setAuth]=useState(null),[password,setPassword]=useState(''),[loggingIn,setLoggingIn]=useState(false),[error,setError]=useState(''),[tab,setTab]=useState('AGY'),[status,setStatus]=useState('connecting');
  function navigate(loggedIn){const target=loggedIn?'/':'/login';if(location.pathname!==target)history.replaceState({},'',target);}
  useEffect(()=>{api('/me').then(s=>{setCsrf(s.csrf);setAuth(true);navigate(true);}).catch(()=>{setAuth(false);navigate(false);});const expire=()=>{setAuth(false);setCsrf('');navigate(false);};window.addEventListener('session-expired',expire);const viewport=()=>{document.documentElement.style.setProperty('--app-height',`${window.visualViewport?.height||window.innerHeight}px`);document.documentElement.classList.toggle('keyboard-open',!!window.visualViewport&&window.innerHeight-window.visualViewport.height>150);};viewport();window.addEventListener('resize',viewport);window.visualViewport?.addEventListener('resize',viewport);navigator.serviceWorker?.register('/sw.js');return()=>{window.removeEventListener('session-expired',expire);window.removeEventListener('resize',viewport);window.visualViewport?.removeEventListener('resize',viewport);};},[]);
  function switchTab(name){if(name===tab)return;if(window.agyHasUnsavedChanges&&!window.confirm('Discard unsaved changes?'))return;setTab(name);}
  async function login(e){e.preventDefault();setLoggingIn(true);setError('');try{const s=await api('/login',{method:'POST',body:{password}});setCsrf(s.csrf);setPassword('');setAuth(true);navigate(true);}catch(e){setError(e.message);}finally{setLoggingIn(false);}}
  async function logout(){try{await api('/logout',{method:'POST',body:{}});setAuth(false);setCsrf('');navigate(false);}catch(e){setError(e.message);}}
  if(auth===null)return <div className="loading"><Brand/><span>Connecting to your workspace…</span></div>;
  if(!auth)return <div className="login-page"><header><Brand/><span className="private-label"><Lock size={12}/>PRIVATE ACCESS</span></header><main className="login-main"><div className="login-art"><span className="orbit orbit-one"/><span className="orbit orbit-two"/><span className="orbit orbit-three"/><span className="asterisk">✳</span></div><span className="eyebrow">YOUR AGENT. YOUR SPACE.</span><h1>A little closer<br/>to your workspace.</h1><p>One persistent home for Antigravity.<br/>Ready wherever you are.</p><form onSubmit={login}><label htmlFor="password">Workspace password</label><div className="password-field"><Lock size={17}/><input id="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required placeholder="Enter your password"/></div>{error&&<p className="login-error" role="alert">{error}</p>}<button className="primary" disabled={loggingIn}>{loggingIn?'Opening workspace…':'Open workspace'}<ArrowRight size={17}/></button></form><span className="login-foot"><ShieldCheck size={14}/>Just you and your workspace.</span></main><footer>AGY stays AGY. You stay in control.</footer></div>;
  return <div className="app-shell"><aside className="sidebar"><Brand/><div className="workspace-label"><span className="status-dot"/>Personal workspace</div><nav aria-label="Main navigation">{sections.map(([name,Icon])=><button key={name} aria-current={tab===name?'page':undefined} className={tab===name?'active':''} onClick={()=>switchTab(name)}><Icon size={19}/><span>{name}</span>{tab===name&&<span className="nav-indicator"/>}</button>)}</nav><div className="sidebar-bottom"><span className="private-label"><ShieldCheck size={13}/>PRIVATE · SINGLE USER</span><p>A persistent home.<br/>An agent that stays itself.</p></div></aside><main className="main-shell"><header className="topbar"><div className="mobile-brand"><Brand/></div><div className="desktop-heading"><span className="topbar-prefix">WORKSPACE</span><span className="dim">/</span><span>{tab}</span></div><span className={'connection '+status}><span className="status-dot"/>{status==='connected'?'Connected':status==='connecting'?'Connecting':'Reconnecting'}</span></header><div className="main-content">{error&&<div className="error-toast" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss"><X size={16}/></button></div>}
    <div className="terminal-section" hidden={tab!=='AGY'}><div className="terminal-intro"><div><span className="eyebrow">YOUR PERSISTENT TERMINAL</span><h1>Back to your space<span className="accent">.</span></h1><p>Same workspace. Same session. Pick up where you left off.</p></div><span className="session-pill"><span className="status-dot"/>agy-main</span></div><Terminal visible={tab==='AGY'} onStatus={setStatus}/><div className="terminal-footer"><span><Lock size={12}/>Private workspace</span><span>Start Antigravity with <code>agy</code></span></div></div>
    {tab==='Files'&&<Files onError={setError}/>} {tab==='Memory'&&<Files memory onError={setError}/>} {tab==='Browser'&&<Browser onError={setError}/>} {tab==='Settings'&&<Preferences onError={setError} onLogout={logout}/>}</div><nav className="mobile-nav" aria-label="Mobile navigation">{sections.map(([name,Icon])=><button key={name} aria-current={tab===name?'page':undefined} className={tab===name?'active':''} onClick={()=>switchTab(name)}><Icon size={20}/><span>{name}</span></button>)}</nav></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
